- name: Execute a command on HMC
  hosts: all
  connection: local
  gather_facts: false
  collections:
   - ibm.power_hmc
  vars:
    inventory_hostname: 192.168.0.191
    ansible_user: hscroot
    hmc_password: 
    discovered_interpreter_python: /usr/bin/python3
  tasks:
    - name: Execute a command on HMC
      ibm.power_hmc.hmc_command:
        hmc_host: "{{ inventory_hostname }}"
        hmc_auth:
          username: '{{ ansible_user }}'
          password: '{{ hmc_password }}'
        cmd: "lshmc -V"
    - name: Execute a version check command on HMC
      ibm.power_hmc.hmc_command:
        hmc_host: "{{ inventory_hostname }}"
        hmc_auth:
          username: '{{ ansible_user }}'
          password: '{{ hmc_password }}'
        cmd: "lssyscfg -r lpar -m DR_Server-9009-41A-SN78488F0 -F name,lpar_env,state,os_version"
