---
- name: upgrade from ibmwebsite
  hosts: all
  gather_facts: false
  connection: local
  collections:
    - ibm.power_hmc
  vars:
    inventory_hostname: 192.168.0.191
    ansible_user: hscroot
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  tasks:
    - name: Wait 30 Mins before Update
      pause:
        seconds: 1800

    - name: Update the Power HMC to the V10R2M1041(ifix) build level from ibmwebsite
      hmc_update_upgrade:
          hmc_host: '{{ inventory_hostname }}'
          hmc_auth:
              username: '{{ ansible_user }}'
              password: '{{ hmc_password }}'
          build_config:
              location_type: ibmwebsite
              ptf: vMF71409
          state: updated
